### ISSUE TITLE
Question - Why aren't NAT Gateways used in GovCloud

### ISSUE THREAD

**Issue by dls314** [aws-quickstart/quickstart-aws-vpc#14]
I noticed that NAT Gateways aren't used in GovCloud by the template--NAT instances are used instead.

In the documentation, it says

> If you deploy the Quick Start in a region that doesn’t support NAT gateways, NAT instances are deployed instead.

I can't (yet) find anything about VPCs in GovCloud not supporting NAT Gateway in any of the docs (https://aws.amazon.com/govcloud-us/details/)

Is this an obsolete limitation?

**Comment by santiagocardenas** [comment]
Hi @dls314 ,
VPC NAT Gateways are currently not available in the AWS GovCloud Region.

Thanks,
Santiago
