### ISSUE TITLE
Cryptic error message when # items in AvailabilityZones < NumberOfAZs

### ISSUE THREAD

**Issue by bczoma** [aws-quickstart/quickstart-aws-vpc#16]
Not sure if it is easy to validate this in the template.

E.g listing 2 AZs two but specifying 3:

17:21:10 UTC-0400 | CREATE_FAILED | AWS::CloudFormation::Stack | VPCStack | Template error: Fn::Select cannot select nonexistent value at index 2

**Comment by tlindsay42** [comment]
Unfortunately, there's still no way to test for this in CloudFormation. Closing the issue, but we'll build a rule for this if/when it becomes possible, because we would like to improve this experience.
