### ISSUE TITLE
How you maintain your vpc template?

### ISSUE THREAD

**Issue by mrPsycho** [aws-quickstart/quickstart-aws-vpc#20]
Hello,

i'm just wondering - how do you maintain https://github.com/aws-quickstart/quickstart-aws-vpc/blob/master/templates/aws-vpc.template ? 

does it generated automatically? 

asking, because 3k lines in one file - it is sic!!

**Comment by avattathil** [comment]
We have a CI system that continuously tests on any updates. I will send you more info directly. Closing this issue

**Comment by avattathil** [comment]
We use a tool called taskcat you can find it here taskcat.io
