### ISSUE TITLE
template file should have a more useful file suffix

### ISSUE THREAD

**Issue by khaliddermoumi** [aws-quickstart/quickstart-aws-vpc#24]
Hi, this is a minor change request, but quite helpful for some:

The template file in this project is just named "aws-vpc.template". If you would rename it to f. e. "aws-vpc.template.json", it would work better for people working with the templates in a local IDE.

For example, I am working with IntelliJ on my local computer with those templates, and the CloudFormation plugin is loaded for files with an suffix "*.template.yaml" or "*.template.json". This is  a default and typical setup, not just on this IDE but on others too. Now this isn't a big showstopper, but it would be nice to have this. And btw, you yourself are using other file suffixes in the other quickstart project, such as "*.template.yaml", which work just fine.

**Comment by davmayd** [comment]
The YAML template has been named .template.yaml and the JSON template has been deprecated
