### ISSUE TITLE
Template error: Unable to get mapping for AWSAMIRegionMap::us-gov-west-1::US1604HVM

### ISSUE THREAD

**Issue by b-anani** [aws-quickstart/quickstart-aws-vpc#25]
I am attempting to deploy Tableau Server to AWS gov Cloud and am encountering the following error

```YAML
Template error: Unable to get mapping for AWSAMIRegionMap::us-gov-west-1::US1604HVM
```

not sure why exactly this is happening but I have attached my template file below in case anyone is wanting to review it

[tableau-single-server.txt](https://github.com/aws-quickstart/quickstart-aws-vpc/files/4364225/tableau-single-server.txt)

**Comment by tlindsay42** [comment]
This should have been opened under https://github.com/aws-quickstart/quickstart-tableau-server, but the region map functionality has since been removed
