### ISSUE TITLE
No private subnets does not work with NatGWEnabled

### ISSUE THREAD

**Issue by gargana** [aws-quickstart/quickstart-aws-vpc#30]
**Problem**
"Private Subnets" : False
does not work in conjunction with 
"CreateNATGateways" : True
**Suggested Fix**
Enforce a check to fail this early via "Rules"

**Comment by sadlerwcb** [comment]
FYI this is preventing me and probably others from using the AWS quickstart at https://aws-quickstart.s3.amazonaws.com/quickstart-splunk-enterprise/doc/splunk-enterprise-on-the-aws-cloud.pdf.  What is the suggested workaround?  I spent the last hour tracking it down and came here to create the issue when I should have just looked at the issues here to start :-)

**Comment by tlindsay42** [comment]
Fixed in af52dd7d7f32aea532e5b47b21bd91b178897902
