### ISSUE TITLE
Update AMI to use latest PHP, Wordpress, Apache etc

### ISSUE THREAD

**Issue by dtaylor7** [aws-quickstart/quickstart-aws-vpc#33]

**Comment by vsnyc** [comment]
@dtaylor7 Is this issue opened against the wrong repo? The VPC quick start does not use any AMIs.

**Comment by dtaylor7** [comment]
i presumsed it selected a default ami?

**Comment by vsnyc** [comment]
It only sets up the networking infrastructure: VPC, subnets, route tables, etc. No Amazon EC2 instances are provisioned and hence no AMIs are used.

**Comment by dtaylor7** [comment]
ok apologies
